### ISSUE TITLE
安装optool这步不够详细，我这边一直提示找不到FSArgumentParser.h文件

### ISSUE THREAD

**Issue by gu2890961** [yohunl/weweChatAssitant#3]
安装optool这步不够详细，我这边一直提示找不到FSArgumentParser.h文件
麻烦说详细点，就是说修改那个地址什么的，最好有截图，谢谢！

**Comment by gu2890961** [comment]
optool安成功了，但是找不到砸壳的微信啊，PP助手下载的越狱版还是加密过的，身边没有越狱手机，方便的话发一份最新版的微信砸壳版本，谢谢！  745001999@qq.com

**Comment by yohunl** [comment]
pp助手下载的越狱版本的,其实是砸过壳的,只是不知道它使用了什么方式,包含了是armv7和x86_64两种架构,所以你直接查看是否加密,看到的加密的,但是这个不影响你使用

**Comment by gu2890961** [comment]
嗯，刚刚用了你最新的代码，安装好后打开就闪退了

**Comment by yohunl** [comment]
安装后的闪退,应该是你的签名问题

**Comment by gu2890961** [comment]
真不行啊，签名是没问题的，我怀疑是我下的最新的6.5.3（越狱版）包有问题，能不能把你弄好的ipa发一份给我，我自己再重签名一下。 745001999@qq.com ,非常感谢！

**Comment by yohunl** [comment]
你是越狱手机的话,直接越狱的方式来装,更好呀,就不用制作ipa了
