### ISSUE TITLE
功能列表没内容

### ISSUE THREAD

**Issue by weixingdeng** [yohunl/weweChatAssitant#4]
iPhone 5 
安装后功能列表没有内容 只有下面的一串码
是使用的dylib 不对吗

**Comment by yohunl** [comment]
你要看下源码了,源码中做了些控制,主要是为了避免制作出来的ipa包乱流传.所以,只有gloabalConfig.json文件中已经添加了对应的串号的,才会出现 控制菜单

**Comment by yohunl** [comment]
我提交了最新的代码,将master分支中的通过网络通知功能权限的开关功能去掉了,你重现安装吧,就能直接看到菜单了
