### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by NuolanNuolan** [yohunl/weweChatAssitant#5]
能发我一个最新砸过壳的微信吗?PP助手上面6.5.3的我看了下是加密过的

**Comment by yohunl** [comment]
pp助手上的越狱应用,其实是砸过壳的了,只是它有点奇怪,包含的架构是armv7和x86_64,也不知道这个x86_64怎么来的,
其中的armv7是没有壳的,
所以你下载它后,按照我的步骤操作下来就可以了

**Comment by NuolanNuolan** [comment]
armv7不是只支持iphone4以下的吗

**Comment by NuolanNuolan** [comment]
架构有armv7和arm64 微信最低版本是支持到iOS7的 我的理解是iphone5c及其以下的设备是要使用armv7的

**Comment by NuolanNuolan** [comment]
我不知道我理解的对不对

**Comment by yohunl** [comment]
你的理解是对的
