### ISSUE TITLE
抢红包功能好像暂时没效果

### ISSUE THREAD

**Issue by h0ngyue** [yohunl/weweChatAssitant#6]
首先，谢谢你的分享，装上之后，步数和定位都很好用。但是红包功能打开后还是不能自动抢，不知道是我哪里设置错了还是最新版本的微信不适用了。我当前的微信版本号是6.5.3。
谢谢！

**Comment by yohunl** [comment]
你有出现菜单么,我们使用都是有效果的啊,版本也是最新的6.5.3

**Comment by h0ngyue** [comment]
出现了菜单，其他功能都能用。是不是ios-signer重签名的时候不能改应用的bundle id

**Comment by zhitrend** [comment]
抢红包没效果，请问什么问题呢。经纬度和步数都可以，微信修改了方法名吗？

**Comment by zhitrend** [comment]
被监测出红包插件，不知道是不是这个问题导致的

**Comment by yohunl** [comment]
微信应该是在新版本预置了抢红包功能的检测功能,所以,如果想使用,只能使用之前版本的微信,据我所知,6.3.23版本,是可以的
