### ISSUE TITLE
怎么知道是否注入成功

### ISSUE THREAD

**Issue by zhitrend** [yohunl/weweChatAssitant#7]
你好，我按你的方法注入后安装成功，并且打开后，没有悬浮窗口，想知道怎么查看是否注入成功了

**Comment by yohunl** [comment]
没有悬浮窗口的话,那应该是你没有注入吧
注入成功与否,在你执行optool的时候,就有提示,你也可以使用命令 otool -L WeChat来查看WeChat加载的dylib来确认
